import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "c96507a67440"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recommendation",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("min_temperature", sa.Float(), nullable=False),
        sa.Column("max_temperature", sa.Float(), nullable=False),
        sa.Column("feel", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("outfit", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("activity", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id")
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recommendation")
    # ### end Alembic commands ###
